/*
1.inspired from binary search algo.
2.SEARCHING IN A BINARY TEE INVOLVES VISITING EACH NODE 
3.RIGHT WALA ROOT SE BADA LEFT WALA ROOT SE CHOTA
4.2 CHILDREN AT MOSE
5.THESE TWO ARE BASIC CONDITIONS.
6.
         4
      3     6
    1  5   5  7
       Becoz of 4's 5 it is not binary search tree
7.everything on left of tree is less than root and everything on right of tree is greater than the root.
*/
